#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting.model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Accountancy")]
	public partial class dcAccountancyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsettings_tbl(settings_tbl instance);
    partial void Updatesettings_tbl(settings_tbl instance);
    partial void Deletesettings_tbl(settings_tbl instance);
    partial void Insertroles_tbl(roles_tbl instance);
    partial void Updateroles_tbl(roles_tbl instance);
    partial void Deleteroles_tbl(roles_tbl instance);
    partial void Insertusers_tbl(users_tbl instance);
    partial void Updateusers_tbl(users_tbl instance);
    partial void Deleteusers_tbl(users_tbl instance);
    #endregion
		
		public dcAccountancyDataContext() : 
				base(global::Accounting.Properties.Settings.Default.AccountancyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dcAccountancyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAccountancyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAccountancyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dcAccountancyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<settings_tbl> settings_tbls
		{
			get
			{
				return this.GetTable<settings_tbl>();
			}
		}
		
		public System.Data.Linq.Table<roles_tbl> roles_tbls
		{
			get
			{
				return this.GetTable<roles_tbl>();
			}
		}
		
		public System.Data.Linq.Table<users_tbl> users_tbls
		{
			get
			{
				return this.GetTable<users_tbl>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExistsSettings_tbl")]
		public int ExistsSettings_tbl([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExistSettings", DbType="Bit")] ref System.Nullable<bool> existSettings)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), existSettings);
			existSettings = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillSettings_tbl")]
		public ISingleResult<settings_tbl> FillSettings_tbl()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<settings_tbl>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertSettings_tbl")]
		public int InsertSettings_tbl(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string companyname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codeeghtesadi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codemelli, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string invoiceaddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string invoicephonenumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string invtracephonenumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string smspanelusername, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string smsmpanelpassword, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string smssender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string smsrecivernumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hoshdarsarresidaz, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hoshdarsarresidta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string invtraceaddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(11)")] string usermobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> banksend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> invoicesend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string modiramel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sabt_code, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string logo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string logo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> add_user, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edit_user, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string add_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyname, codeeghtesadi, codemelli, invoiceaddress, invoicephonenumber, invtracephonenumber, smspanelusername, smsmpanelpassword, smssender, smsrecivernumber, hoshdarsarresidaz, hoshdarsarresidta, invtraceaddress, usermobile, banksend, invoicesend, modiramel, sabt_code, logo1, logo2, is_active, add_user, edit_user, add_date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateSettings_tbl")]
		public int UpdateSettings_tbl(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string companyname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codeeghtesadi, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string codemelli, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string invoiceaddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string invoicephonenumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string invtracephonenumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string smspanelusername, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string smsmpanelpassword, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string smssender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string smsrecivernumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hoshdarsarresidaz, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> hoshdarsarresidta, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(250)")] string invtraceaddress, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(11)")] string usermobile, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> banksend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> invoicesend, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string modiramel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sabt_code, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string logo1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string logo2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_active, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> add_user, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edit_user, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string add_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyname, codeeghtesadi, codemelli, invoiceaddress, invoicephonenumber, invtracephonenumber, smspanelusername, smsmpanelpassword, smssender, smsrecivernumber, hoshdarsarresidaz, hoshdarsarresidta, invtraceaddress, usermobile, banksend, invoicesend, modiramel, sabt_code, logo1, logo2, is_active, add_user, edit_user, add_date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DeleteRoles")]
		public int DeleteRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ExistRoles")]
		public int ExistRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Exists", DbType="Bit")] ref System.Nullable<bool> exists)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), exists);
			exists = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillRoles")]
		public ISingleResult<roles_tbl> FillRoles()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<roles_tbl>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FillRolesById")]
		public ISingleResult<roles_tbl> FillRolesById([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleid);
			return ((ISingleResult<roles_tbl>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertRoles")]
		public int InsertRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> depot, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bank, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> person, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> factor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> settings, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_active, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> add_user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edit_user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string add_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, depot, bank, person, factor, settings, user, is_active, add_user, edit_user, add_date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UpdateRoles")]
		public int UpdateRoles([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> depot, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> bank, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> person, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> factor, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> settings, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_active, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> add_user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edit_user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string add_date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleid, name, depot, bank, person, factor, settings, user, is_active, add_user, edit_user, add_date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_DeleteuserByID")]
		public int sp_DeleteuserByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FillUsers")]
		public ISingleResult<users_tbl> sp_FillUsers()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<users_tbl>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_FindUserByID")]
		public ISingleResult<users_tbl> sp_FindUserByID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid);
			return ((ISingleResult<users_tbl>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserNameCheck")]
		public int sp_UserNameCheck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Check", DbType="Bit")] ref System.Nullable<bool> check, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), check, username);
			check = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UsersExists")]
		public int sp_UsersExists([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExistUsers", DbType="Bit")] ref System.Nullable<bool> existUsers)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), existUsers);
			existUsers = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.updateusers_tbl")]
		public int updateusers_tbl([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> userid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userpassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_actve, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string family, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string user_address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string add_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> add_user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edit_user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userid, roleid, username, userpassword, is_actve, name, family, user_address, email, phone, mobile, add_date, add_user, edit_user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertusers_tbl")]
		public int insertusers_tbl([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> roleid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userpassword, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> is_actve, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string family, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string user_address, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string add_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> add_user, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> edit_user)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), roleid, username, userpassword, is_actve, name, family, user_address, email, phone, mobile, add_date, add_user, edit_user);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_UserPassCheck")]
		public int sp_UserPassCheck([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckPassword", DbType="Bit")] ref System.Nullable<bool> checkPassword, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="NVarChar(20)")] string userName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), checkPassword, userName);
			checkPassword = ((System.Nullable<bool>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.settings_tbl")]
	public sealed partial class settings_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _settingsID;
		
		private string _companyname;
		
		private string _codeeghtesadi;
		
		private string _codemelli;
		
		private string _invoiceaddress;
		
		private string _invoicephonenumber;
		
		private string _invtracephonenumber;
		
		private string _smspanelusername;
		
		private string _smsmpanelpassword;
		
		private string _smssender;
		
		private string _smsrecivernumber;
		
		private System.Nullable<int> _hoshdarsarresidaz;
		
		private System.Nullable<int> _hoshdarsarresidta;
		
		private string _invtraceaddress;
		
		private string _usermobile;
		
		private System.Nullable<bool> _banksend;
		
		private System.Nullable<bool> _invoicesend;
		
		private string _modiramel;
		
		private string _sabt_code;
		
		private string _logo1;
		
		private string _logo2;
		
		private System.Nullable<bool> _is_active;
		
		private System.Nullable<int> _add_user;
		
		private System.Nullable<int> _edit_user;
		
		private string _add_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsettingsIDChanging(int value);
    partial void OnsettingsIDChanged();
    partial void OncompanynameChanging(string value);
    partial void OncompanynameChanged();
    partial void OncodeeghtesadiChanging(string value);
    partial void OncodeeghtesadiChanged();
    partial void OncodemelliChanging(string value);
    partial void OncodemelliChanged();
    partial void OninvoiceaddressChanging(string value);
    partial void OninvoiceaddressChanged();
    partial void OninvoicephonenumberChanging(string value);
    partial void OninvoicephonenumberChanged();
    partial void OninvtracephonenumberChanging(string value);
    partial void OninvtracephonenumberChanged();
    partial void OnsmspanelusernameChanging(string value);
    partial void OnsmspanelusernameChanged();
    partial void OnsmsmpanelpasswordChanging(string value);
    partial void OnsmsmpanelpasswordChanged();
    partial void OnsmssenderChanging(string value);
    partial void OnsmssenderChanged();
    partial void OnsmsrecivernumberChanging(string value);
    partial void OnsmsrecivernumberChanged();
    partial void OnhoshdarsarresidazChanging(System.Nullable<int> value);
    partial void OnhoshdarsarresidazChanged();
    partial void OnhoshdarsarresidtaChanging(System.Nullable<int> value);
    partial void OnhoshdarsarresidtaChanged();
    partial void OninvtraceaddressChanging(string value);
    partial void OninvtraceaddressChanged();
    partial void OnusermobileChanging(string value);
    partial void OnusermobileChanged();
    partial void OnbanksendChanging(System.Nullable<bool> value);
    partial void OnbanksendChanged();
    partial void OninvoicesendChanging(System.Nullable<bool> value);
    partial void OninvoicesendChanged();
    partial void OnmodiramelChanging(string value);
    partial void OnmodiramelChanged();
    partial void Onsabt_codeChanging(string value);
    partial void Onsabt_codeChanged();
    partial void Onlogo1Changing(string value);
    partial void Onlogo1Changed();
    partial void Onlogo2Changing(string value);
    partial void Onlogo2Changed();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    partial void Onadd_userChanging(System.Nullable<int> value);
    partial void Onadd_userChanged();
    partial void Onedit_userChanging(System.Nullable<int> value);
    partial void Onedit_userChanged();
    partial void Onadd_dateChanging(string value);
    partial void Onadd_dateChanged();
    #endregion
		
		public settings_tbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingsID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int settingsID
		{
			get
			{
				return this._settingsID;
			}
			set
			{
				if ((this._settingsID != value))
				{
					this.OnsettingsIDChanging(value);
					this.SendPropertyChanging();
					this._settingsID = value;
					this.SendPropertyChanged("settingsID");
					this.OnsettingsIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyname", DbType="NVarChar(150)")]
		public string companyname
		{
			get
			{
				return this._companyname;
			}
			set
			{
				if ((this._companyname != value))
				{
					this.OncompanynameChanging(value);
					this.SendPropertyChanging();
					this._companyname = value;
					this.SendPropertyChanged("companyname");
					this.OncompanynameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codeeghtesadi", DbType="NVarChar(50)")]
		public string codeeghtesadi
		{
			get
			{
				return this._codeeghtesadi;
			}
			set
			{
				if ((this._codeeghtesadi != value))
				{
					this.OncodeeghtesadiChanging(value);
					this.SendPropertyChanging();
					this._codeeghtesadi = value;
					this.SendPropertyChanged("codeeghtesadi");
					this.OncodeeghtesadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_codemelli", DbType="NVarChar(50)")]
		public string codemelli
		{
			get
			{
				return this._codemelli;
			}
			set
			{
				if ((this._codemelli != value))
				{
					this.OncodemelliChanging(value);
					this.SendPropertyChanging();
					this._codemelli = value;
					this.SendPropertyChanged("codemelli");
					this.OncodemelliChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoiceaddress", DbType="NVarChar(250)")]
		public string invoiceaddress
		{
			get
			{
				return this._invoiceaddress;
			}
			set
			{
				if ((this._invoiceaddress != value))
				{
					this.OninvoiceaddressChanging(value);
					this.SendPropertyChanging();
					this._invoiceaddress = value;
					this.SendPropertyChanged("invoiceaddress");
					this.OninvoiceaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoicephonenumber", DbType="NVarChar(20)")]
		public string invoicephonenumber
		{
			get
			{
				return this._invoicephonenumber;
			}
			set
			{
				if ((this._invoicephonenumber != value))
				{
					this.OninvoicephonenumberChanging(value);
					this.SendPropertyChanging();
					this._invoicephonenumber = value;
					this.SendPropertyChanged("invoicephonenumber");
					this.OninvoicephonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invtracephonenumber", DbType="NVarChar(20)")]
		public string invtracephonenumber
		{
			get
			{
				return this._invtracephonenumber;
			}
			set
			{
				if ((this._invtracephonenumber != value))
				{
					this.OninvtracephonenumberChanging(value);
					this.SendPropertyChanging();
					this._invtracephonenumber = value;
					this.SendPropertyChanged("invtracephonenumber");
					this.OninvtracephonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smspanelusername", DbType="NVarChar(100)")]
		public string smspanelusername
		{
			get
			{
				return this._smspanelusername;
			}
			set
			{
				if ((this._smspanelusername != value))
				{
					this.OnsmspanelusernameChanging(value);
					this.SendPropertyChanging();
					this._smspanelusername = value;
					this.SendPropertyChanged("smspanelusername");
					this.OnsmspanelusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smsmpanelpassword", DbType="NVarChar(200)")]
		public string smsmpanelpassword
		{
			get
			{
				return this._smsmpanelpassword;
			}
			set
			{
				if ((this._smsmpanelpassword != value))
				{
					this.OnsmsmpanelpasswordChanging(value);
					this.SendPropertyChanging();
					this._smsmpanelpassword = value;
					this.SendPropertyChanged("smsmpanelpassword");
					this.OnsmsmpanelpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smssender", DbType="NVarChar(20)")]
		public string smssender
		{
			get
			{
				return this._smssender;
			}
			set
			{
				if ((this._smssender != value))
				{
					this.OnsmssenderChanging(value);
					this.SendPropertyChanging();
					this._smssender = value;
					this.SendPropertyChanged("smssender");
					this.OnsmssenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smsrecivernumber", DbType="NVarChar(20)")]
		public string smsrecivernumber
		{
			get
			{
				return this._smsrecivernumber;
			}
			set
			{
				if ((this._smsrecivernumber != value))
				{
					this.OnsmsrecivernumberChanging(value);
					this.SendPropertyChanging();
					this._smsrecivernumber = value;
					this.SendPropertyChanged("smsrecivernumber");
					this.OnsmsrecivernumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoshdarsarresidaz", DbType="Int")]
		public System.Nullable<int> hoshdarsarresidaz
		{
			get
			{
				return this._hoshdarsarresidaz;
			}
			set
			{
				if ((this._hoshdarsarresidaz != value))
				{
					this.OnhoshdarsarresidazChanging(value);
					this.SendPropertyChanging();
					this._hoshdarsarresidaz = value;
					this.SendPropertyChanged("hoshdarsarresidaz");
					this.OnhoshdarsarresidazChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoshdarsarresidta", DbType="Int")]
		public System.Nullable<int> hoshdarsarresidta
		{
			get
			{
				return this._hoshdarsarresidta;
			}
			set
			{
				if ((this._hoshdarsarresidta != value))
				{
					this.OnhoshdarsarresidtaChanging(value);
					this.SendPropertyChanging();
					this._hoshdarsarresidta = value;
					this.SendPropertyChanged("hoshdarsarresidta");
					this.OnhoshdarsarresidtaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invtraceaddress", DbType="NVarChar(250)")]
		public string invtraceaddress
		{
			get
			{
				return this._invtraceaddress;
			}
			set
			{
				if ((this._invtraceaddress != value))
				{
					this.OninvtraceaddressChanging(value);
					this.SendPropertyChanging();
					this._invtraceaddress = value;
					this.SendPropertyChanged("invtraceaddress");
					this.OninvtraceaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usermobile", DbType="NVarChar(11)")]
		public string usermobile
		{
			get
			{
				return this._usermobile;
			}
			set
			{
				if ((this._usermobile != value))
				{
					this.OnusermobileChanging(value);
					this.SendPropertyChanging();
					this._usermobile = value;
					this.SendPropertyChanged("usermobile");
					this.OnusermobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_banksend", DbType="Bit")]
		public System.Nullable<bool> banksend
		{
			get
			{
				return this._banksend;
			}
			set
			{
				if ((this._banksend != value))
				{
					this.OnbanksendChanging(value);
					this.SendPropertyChanging();
					this._banksend = value;
					this.SendPropertyChanged("banksend");
					this.OnbanksendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_invoicesend", DbType="Bit")]
		public System.Nullable<bool> invoicesend
		{
			get
			{
				return this._invoicesend;
			}
			set
			{
				if ((this._invoicesend != value))
				{
					this.OninvoicesendChanging(value);
					this.SendPropertyChanging();
					this._invoicesend = value;
					this.SendPropertyChanged("invoicesend");
					this.OninvoicesendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modiramel", DbType="NVarChar(50)")]
		public string modiramel
		{
			get
			{
				return this._modiramel;
			}
			set
			{
				if ((this._modiramel != value))
				{
					this.OnmodiramelChanging(value);
					this.SendPropertyChanging();
					this._modiramel = value;
					this.SendPropertyChanged("modiramel");
					this.OnmodiramelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sabt_code", DbType="NVarChar(50)")]
		public string sabt_code
		{
			get
			{
				return this._sabt_code;
			}
			set
			{
				if ((this._sabt_code != value))
				{
					this.Onsabt_codeChanging(value);
					this.SendPropertyChanging();
					this._sabt_code = value;
					this.SendPropertyChanged("sabt_code");
					this.Onsabt_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo1", DbType="NVarChar(MAX)")]
		public string logo1
		{
			get
			{
				return this._logo1;
			}
			set
			{
				if ((this._logo1 != value))
				{
					this.Onlogo1Changing(value);
					this.SendPropertyChanging();
					this._logo1 = value;
					this.SendPropertyChanged("logo1");
					this.Onlogo1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo2", DbType="NVarChar(MAX)")]
		public string logo2
		{
			get
			{
				return this._logo2;
			}
			set
			{
				if ((this._logo2 != value))
				{
					this.Onlogo2Changing(value);
					this.SendPropertyChanging();
					this._logo2 = value;
					this.SendPropertyChanged("logo2");
					this.Onlogo2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_user", DbType="Int")]
		public System.Nullable<int> add_user
		{
			get
			{
				return this._add_user;
			}
			set
			{
				if ((this._add_user != value))
				{
					this.Onadd_userChanging(value);
					this.SendPropertyChanging();
					this._add_user = value;
					this.SendPropertyChanged("add_user");
					this.Onadd_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edit_user", DbType="Int")]
		public System.Nullable<int> edit_user
		{
			get
			{
				return this._edit_user;
			}
			set
			{
				if ((this._edit_user != value))
				{
					this.Onedit_userChanging(value);
					this.SendPropertyChanging();
					this._edit_user = value;
					this.SendPropertyChanged("edit_user");
					this.Onedit_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_date", DbType="NVarChar(50)")]
		public string add_date
		{
			get
			{
				return this._add_date;
			}
			set
			{
				if ((this._add_date != value))
				{
					this.Onadd_dateChanging(value);
					this.SendPropertyChanging();
					this._add_date = value;
					this.SendPropertyChanged("add_date");
					this.Onadd_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		private void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		private void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.roles_tbl")]
	public sealed partial class roles_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _roleid;
		
		private string _rolename;
		
		private System.Nullable<bool> _depotpermission;
		
		private System.Nullable<bool> _bankpermission;
		
		private System.Nullable<bool> _personpermission;
		
		private System.Nullable<bool> _factorpermission;
		
		private System.Nullable<bool> _settingspermission;
		
		private System.Nullable<bool> _userpermission;
		
		private System.Nullable<bool> _is_active;
		
		private System.Nullable<int> _add_user;
		
		private System.Nullable<int> _edit_user;
		
		private string _add_date;
		
		private EntitySet<users_tbl> _users_tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnroleidChanging(int value);
    partial void OnroleidChanged();
    partial void OnrolenameChanging(string value);
    partial void OnrolenameChanged();
    partial void OndepotpermissionChanging(System.Nullable<bool> value);
    partial void OndepotpermissionChanged();
    partial void OnbankpermissionChanging(System.Nullable<bool> value);
    partial void OnbankpermissionChanged();
    partial void OnpersonpermissionChanging(System.Nullable<bool> value);
    partial void OnpersonpermissionChanged();
    partial void OnfactorpermissionChanging(System.Nullable<bool> value);
    partial void OnfactorpermissionChanged();
    partial void OnsettingspermissionChanging(System.Nullable<bool> value);
    partial void OnsettingspermissionChanged();
    partial void OnuserpermissionChanging(System.Nullable<bool> value);
    partial void OnuserpermissionChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    partial void Onadd_userChanging(System.Nullable<int> value);
    partial void Onadd_userChanged();
    partial void Onedit_userChanging(System.Nullable<int> value);
    partial void Onedit_userChanged();
    partial void Onadd_dateChanging(string value);
    partial void Onadd_dateChanged();
    #endregion
		
		public roles_tbl()
		{
			this._users_tbls = new EntitySet<users_tbl>(new Action<users_tbl>(this.attach_users_tbls), new Action<users_tbl>(this.detach_users_tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rolename", DbType="NVarChar(50)")]
		public string rolename
		{
			get
			{
				return this._rolename;
			}
			set
			{
				if ((this._rolename != value))
				{
					this.OnrolenameChanging(value);
					this.SendPropertyChanging();
					this._rolename = value;
					this.SendPropertyChanged("rolename");
					this.OnrolenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depotpermission", DbType="Bit")]
		public System.Nullable<bool> depotpermission
		{
			get
			{
				return this._depotpermission;
			}
			set
			{
				if ((this._depotpermission != value))
				{
					this.OndepotpermissionChanging(value);
					this.SendPropertyChanging();
					this._depotpermission = value;
					this.SendPropertyChanged("depotpermission");
					this.OndepotpermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bankpermission", DbType="Bit")]
		public System.Nullable<bool> bankpermission
		{
			get
			{
				return this._bankpermission;
			}
			set
			{
				if ((this._bankpermission != value))
				{
					this.OnbankpermissionChanging(value);
					this.SendPropertyChanging();
					this._bankpermission = value;
					this.SendPropertyChanged("bankpermission");
					this.OnbankpermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_personpermission", DbType="Bit")]
		public System.Nullable<bool> personpermission
		{
			get
			{
				return this._personpermission;
			}
			set
			{
				if ((this._personpermission != value))
				{
					this.OnpersonpermissionChanging(value);
					this.SendPropertyChanging();
					this._personpermission = value;
					this.SendPropertyChanged("personpermission");
					this.OnpersonpermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_factorpermission", DbType="Bit")]
		public System.Nullable<bool> factorpermission
		{
			get
			{
				return this._factorpermission;
			}
			set
			{
				if ((this._factorpermission != value))
				{
					this.OnfactorpermissionChanging(value);
					this.SendPropertyChanging();
					this._factorpermission = value;
					this.SendPropertyChanged("factorpermission");
					this.OnfactorpermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_settingspermission", DbType="Bit")]
		public System.Nullable<bool> settingspermission
		{
			get
			{
				return this._settingspermission;
			}
			set
			{
				if ((this._settingspermission != value))
				{
					this.OnsettingspermissionChanging(value);
					this.SendPropertyChanging();
					this._settingspermission = value;
					this.SendPropertyChanged("settingspermission");
					this.OnsettingspermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userpermission", DbType="Bit")]
		public System.Nullable<bool> userpermission
		{
			get
			{
				return this._userpermission;
			}
			set
			{
				if ((this._userpermission != value))
				{
					this.OnuserpermissionChanging(value);
					this.SendPropertyChanging();
					this._userpermission = value;
					this.SendPropertyChanged("userpermission");
					this.OnuserpermissionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
		public System.Nullable<bool> is_active
		{
			get
			{
				return this._is_active;
			}
			set
			{
				if ((this._is_active != value))
				{
					this.Onis_activeChanging(value);
					this.SendPropertyChanging();
					this._is_active = value;
					this.SendPropertyChanged("is_active");
					this.Onis_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_user", DbType="Int")]
		public System.Nullable<int> add_user
		{
			get
			{
				return this._add_user;
			}
			set
			{
				if ((this._add_user != value))
				{
					this.Onadd_userChanging(value);
					this.SendPropertyChanging();
					this._add_user = value;
					this.SendPropertyChanged("add_user");
					this.Onadd_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edit_user", DbType="Int")]
		public System.Nullable<int> edit_user
		{
			get
			{
				return this._edit_user;
			}
			set
			{
				if ((this._edit_user != value))
				{
					this.Onedit_userChanging(value);
					this.SendPropertyChanging();
					this._edit_user = value;
					this.SendPropertyChanged("edit_user");
					this.Onedit_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_date", DbType="NVarChar(50)")]
		public string add_date
		{
			get
			{
				return this._add_date;
			}
			set
			{
				if ((this._add_date != value))
				{
					this.Onadd_dateChanging(value);
					this.SendPropertyChanging();
					this._add_date = value;
					this.SendPropertyChanged("add_date");
					this.Onadd_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="roles_tbl_users_tbl", Storage="_users_tbls", ThisKey="roleid", OtherKey="roleid")]
		public EntitySet<users_tbl> users_tbls
		{
			get
			{
				return this._users_tbls;
			}
			set
			{
				this._users_tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		private void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		private void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_users_tbls(users_tbl entity)
		{
			this.SendPropertyChanging();
			entity.roles_tbl = this;
		}
		
		private void detach_users_tbls(users_tbl entity)
		{
			this.SendPropertyChanging();
			entity.roles_tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users_tbl")]
	public sealed partial class users_tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _userid;
		
		private System.Nullable<int> _roleid;
		
		private string _username;
		
		private string _userpassword;
		
		private System.Nullable<bool> _is_actve;
		
		private string _name;
		
		private string _family;
		
		private string _u_address;
		
		private string _email;
		
		private string _phone;
		
		private string _mobile;
		
		private string _add_date;
		
		private System.Nullable<int> _add_user;
		
		private System.Nullable<int> _edit_user;
		
		private EntityRef<roles_tbl> _roles_tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(int value);
    partial void OnuseridChanged();
    partial void OnroleidChanging(System.Nullable<int> value);
    partial void OnroleidChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnuserpasswordChanging(string value);
    partial void OnuserpasswordChanged();
    partial void Onis_actveChanging(System.Nullable<bool> value);
    partial void Onis_actveChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnfamilyChanging(string value);
    partial void OnfamilyChanged();
    partial void Onu_addressChanging(string value);
    partial void Onu_addressChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void Onadd_dateChanging(string value);
    partial void Onadd_dateChanged();
    partial void Onadd_userChanging(System.Nullable<int> value);
    partial void Onadd_userChanged();
    partial void Onedit_userChanging(System.Nullable<int> value);
    partial void Onedit_userChanged();
    #endregion
		
		public users_tbl()
		{
			this._roles_tbl = default(EntityRef<roles_tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roleid", DbType="Int")]
		public System.Nullable<int> roleid
		{
			get
			{
				return this._roleid;
			}
			set
			{
				if ((this._roleid != value))
				{
					if (this._roles_tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnroleidChanging(value);
					this.SendPropertyChanging();
					this._roleid = value;
					this.SendPropertyChanged("roleid");
					this.OnroleidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userpassword", DbType="NVarChar(50)")]
		public string userpassword
		{
			get
			{
				return this._userpassword;
			}
			set
			{
				if ((this._userpassword != value))
				{
					this.OnuserpasswordChanging(value);
					this.SendPropertyChanging();
					this._userpassword = value;
					this.SendPropertyChanged("userpassword");
					this.OnuserpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_actve", DbType="Bit")]
		public System.Nullable<bool> is_actve
		{
			get
			{
				return this._is_actve;
			}
			set
			{
				if ((this._is_actve != value))
				{
					this.Onis_actveChanging(value);
					this.SendPropertyChanging();
					this._is_actve = value;
					this.SendPropertyChanged("is_actve");
					this.Onis_actveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_family", DbType="NVarChar(50)")]
		public string family
		{
			get
			{
				return this._family;
			}
			set
			{
				if ((this._family != value))
				{
					this.OnfamilyChanging(value);
					this.SendPropertyChanging();
					this._family = value;
					this.SendPropertyChanged("family");
					this.OnfamilyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_address", DbType="NVarChar(150)")]
		public string u_address
		{
			get
			{
				return this._u_address;
			}
			set
			{
				if ((this._u_address != value))
				{
					this.Onu_addressChanging(value);
					this.SendPropertyChanging();
					this._u_address = value;
					this.SendPropertyChanged("u_address");
					this.Onu_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="NVarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="NVarChar(20)")]
		public string mobile
		{
			get
			{
				return this._mobile;
			}
			set
			{
				if ((this._mobile != value))
				{
					this.OnmobileChanging(value);
					this.SendPropertyChanging();
					this._mobile = value;
					this.SendPropertyChanged("mobile");
					this.OnmobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_date", DbType="NVarChar(20)")]
		public string add_date
		{
			get
			{
				return this._add_date;
			}
			set
			{
				if ((this._add_date != value))
				{
					this.Onadd_dateChanging(value);
					this.SendPropertyChanging();
					this._add_date = value;
					this.SendPropertyChanged("add_date");
					this.Onadd_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_user", DbType="Int")]
		public System.Nullable<int> add_user
		{
			get
			{
				return this._add_user;
			}
			set
			{
				if ((this._add_user != value))
				{
					this.Onadd_userChanging(value);
					this.SendPropertyChanging();
					this._add_user = value;
					this.SendPropertyChanged("add_user");
					this.Onadd_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edit_user", DbType="Int")]
		public System.Nullable<int> edit_user
		{
			get
			{
				return this._edit_user;
			}
			set
			{
				if ((this._edit_user != value))
				{
					this.Onedit_userChanging(value);
					this.SendPropertyChanging();
					this._edit_user = value;
					this.SendPropertyChanged("edit_user");
					this.Onedit_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="roles_tbl_users_tbl", Storage="_roles_tbl", ThisKey="roleid", OtherKey="roleid", IsForeignKey=true)]
		public roles_tbl roles_tbl
		{
			get
			{
				return this._roles_tbl.Entity;
			}
			set
			{
				roles_tbl previousValue = this._roles_tbl.Entity;
				if (((previousValue != value) 
							|| (this._roles_tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._roles_tbl.Entity = null;
						previousValue.users_tbls.Remove(this);
					}
					this._roles_tbl.Entity = value;
					if ((value != null))
					{
						value.users_tbls.Add(this);
						this._roleid = value.roleid;
					}
					else
					{
						this._roleid = default(Nullable<int>);
					}
					this.SendPropertyChanged("roles_tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		private void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		private void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
